/* ============================================================
   Maths for All — Practice problem bank: LINEAR ALGEBRA
   Same format as js/practice-data.js (load that file first).
   Keys: la-ch1 … la-ch10 (one per chapter of linear-algebra.html)
   ============================================================ */
window.PRACTICE_DATA = window.PRACTICE_DATA || {};
(function (P) {
  var R = String.raw;

  P["la-ch1"] = [
    { id: "la1-1", type: "concept",
      q: R`Can the dot product of two <em>non-zero</em> vectors be zero? What does it mean geometrically?`,
      hint: R`Recall $\mathbf{u}\cdot\mathbf{v} = \|\mathbf{u}\|\|\mathbf{v}\|\cos\theta$.`,
      steps: [R`With non-zero lengths, the product is zero only if $\cos\theta = 0$.`, R`That means $\theta = 90^\circ$.`],
      answer: R`Yes — the vectors are orthogonal.` },
    { id: "la1-2", type: "concept",
      q: R`If $\mathbf{u}\cdot\mathbf{v} = \|\mathbf{u}\|\,\|\mathbf{v}\|$, what can you say about $\mathbf{u}$ and $\mathbf{v}$?`,
      hint: R`When does Cauchy–Schwarz hold with equality?`,
      steps: [R`$\cos\theta = 1$, so $\theta = 0$.`],
      answer: R`They point in the same direction ($\mathbf{v} = c\,\mathbf{u}$ with $c>0$).` },
    { id: "la1-3", type: "computation",
      q: R`Find the angle between $\mathbf{u}=(1,2,2)$ and $\mathbf{v}=(4,0,3)$.`,
      hint: R`Compute the dot product and both norms.`,
      steps: [R`$\mathbf{u}\cdot\mathbf{v} = 4 + 0 + 6 = 10$.`, R`$\|\mathbf{u}\| = \sqrt{1+4+4} = 3,\ \|\mathbf{v}\| = \sqrt{16+9} = 5$.`, R`$\cos\theta = \frac{10}{15} = \frac23$.`],
      answer: R`$\theta = \arccos(2/3) \approx 48.2^\circ$.` },
    { id: "la1-4", type: "computation",
      q: R`Compute the cross product $(1,2,3)\times(4,5,6)$.`,
      hint: R`Use the determinant rule component by component.`,
      steps: [R`$x$: $2\cdot6 - 3\cdot5 = -3$.`, R`$y$: $3\cdot4 - 1\cdot6 = 6$.`, R`$z$: $1\cdot5 - 2\cdot4 = -3$.`],
      answer: R`$(-3,\ 6,\ -3)$.` },
    { id: "la1-5", type: "interview",
      q: R`<strong>Search ranking.</strong> Documents $d_1=(1,1,0)$, $d_2=(1,0,1)$ and query $q=(2,1,0)$ are term-count vectors. Rank the documents by cosine similarity. Why cosine and not Euclidean distance?`,
      hint: R`Compute $\cos(q,d_i)=\frac{q\cdot d_i}{\|q\|\|d_i\|}$.`,
      steps: [R`$\|q\|=\sqrt5,\ \|d_1\|=\|d_2\|=\sqrt2$.`, R`$q\cdot d_1 = 3 \Rightarrow \cos = \frac{3}{\sqrt{10}} \approx 0.949$.`, R`$q\cdot d_2 = 2 \Rightarrow \cos = \frac{2}{\sqrt{10}} \approx 0.632$.`, R`Cosine ignores length, so a long document isn’t favoured just for having bigger counts.`],
      answer: R`$d_1$ ranks first. Cosine compares direction (topic), not magnitude (document length).` }
  ];

  P["la-ch2"] = [
    { id: "la2-1", type: "concept",
      q: R`What is the span of a single non-zero vector in $\mathbb{R}^3$?`,
      hint: R`All scalar multiples $c\mathbf{v}$.`,
      steps: [R`$\text{span}\{\mathbf{v}\} = \{c\mathbf{v} : c\in\mathbb{R}\}$.`],
      answer: R`A line through the origin.` },
    { id: "la2-2", type: "concept",
      q: R`Are $(1,2)$ and $(2,4)$ linearly independent?`,
      hint: R`Is one a scalar multiple of the other?`,
      steps: [R`$(2,4) = 2\,(1,2)$, so $2\mathbf{v}_1 - \mathbf{v}_2 = \mathbf{0}$ is a non-trivial relation.`],
      answer: R`No — they are dependent.` },
    { id: "la2-3", type: "computation",
      q: R`Is $(5,7)$ in $\text{span}\{(1,1),\,(1,-1)\}$? If so, find the coefficients.`,
      hint: R`Solve $a(1,1)+b(1,-1) = (5,7)$.`,
      steps: [R`$a+b=5$ and $a-b=7$.`, R`Add: $2a=12 \Rightarrow a=6$. Then $b=-1$.`, R`Check: $6(1,1) - (1,-1) = (5,7)$ ✓.`],
      answer: R`Yes: $(5,7) = 6(1,1) - 1\,(1,-1)$.` },
    { id: "la2-4", type: "computation",
      q: R`Find a basis and the dimension of the subspace $W=\{(x,y,z): x+y+z=0\}$.`,
      hint: R`Solve for $x$ in terms of the free variables $y,z$.`,
      steps: [R`$x=-y-z$, so $(x,y,z)=y(-1,1,0)+z(-1,0,1)$.`, R`These two vectors are independent and span $W$.`],
      answer: R`Basis $\{(-1,1,0),(-1,0,1)\}$, $\dim W = 2$.` },
    { id: "la2-5", type: "interview",
      q: R`<strong>Data-science screen.</strong> A regression design matrix has columns $x_1,\ x_2,\ x_3 = x_1 + x_2$. What goes wrong, and what is it called?`,
      hint: R`Look at the rank of the matrix and of $X^TX$.`,
      steps: [R`$x_3$ lies in the span of $x_1,x_2$, so the columns are dependent: rank $=2<3$.`, R`Then $X^TX$ is singular, so $(X^TX)^{-1}$ does not exist.`, R`The weights are not unique: add $t$ to $w_1,w_2$ and subtract $t$ from $w_3$ for the same predictions.`],
      answer: R`Perfect multicollinearity: drop or combine the redundant feature, or use regularisation (ridge).` }
  ];

  P["la-ch3"] = [
    { id: "la3-1", type: "concept",
      q: R`How many solutions can a linear system have?`,
      hint: R`Think of two lines in the plane.`,
      steps: [R`Lines can intersect in a point, be parallel, or coincide.`],
      answer: R`0, exactly 1, or infinitely many — never exactly 2.` },
    { id: "la3-2", type: "concept",
      q: R`After row reduction you reach a row $[\,0\ 0\ 0\mid 1\,]$. What does this tell you?`,
      hint: R`Translate the row back into an equation.`,
      steps: [R`It reads $0x+0y+0z = 1$, i.e. $0=1$.`],
      answer: R`The system is inconsistent (no solution).` },
    { id: "la3-3", type: "computation",
      q: R`Solve $x+y=3$, $\ 2x-y=3$.`,
      hint: R`Add the equations to eliminate $y$.`,
      steps: [R`Adding: $3x = 6 \Rightarrow x=2$.`, R`Then $y = 3 - x = 1$.`],
      answer: R`$(x,y)=(2,1)$.` },
    { id: "la3-4", type: "computation",
      q: R`Find the inverse of $A=\begin{bmatrix}2&1\\5&3\end{bmatrix}$.`,
      hint: R`For $2\times2$: $A^{-1}=\frac{1}{ad-bc}\begin{bmatrix}d&-b\\-c&a\end{bmatrix}$.`,
      steps: [R`$\det A = 2\cdot3 - 1\cdot5 = 1$.`, R`Swap the diagonal, negate the off-diagonal.`],
      answer: R`$A^{-1}=\begin{bmatrix}3&-1\\-5&2\end{bmatrix}$.` },
    { id: "la3-5", type: "interview",
      q: R`<strong>Systems at scale.</strong> You must solve $A\mathbf{x}=\mathbf{b}_i$ for 1000 different right-hand sides, $A$ being $n\times n$. What do you do, and what does it cost versus doing elimination each time?`,
      hint: R`Factor once, solve many times.`,
      steps: [R`Gaussian elimination costs $O(n^3)$.`, R`Compute an LU factorisation $A = LU$ once: $O(n^3)$.`, R`For each $\mathbf{b}_i$, do forward then back substitution: $O(n^2)$.`, R`Total $O(n^3 + 1000\,n^2)$ instead of $O(1000\,n^3)$. (Don’t form $A^{-1}$ explicitly: less stable, no cheaper.)`],
      answer: R`Factor once with LU; each extra solve is only $O(n^2)$.` }
  ];

  P["la-ch4"] = [
    { id: "la4-1", type: "concept",
      q: R`Is $T(\mathbf{x}) = \mathbf{x} + (1,0)$ a linear transformation of $\mathbb{R}^2$?`,
      hint: R`Every linear map sends $\mathbf{0}$ to $\mathbf{0}$.`,
      steps: [R`$T(\mathbf{0}) = (1,0) \ne \mathbf{0}$.`],
      answer: R`No — it is affine (a translation), not linear.` },
    { id: "la4-2", type: "concept",
      q: R`Where does a $90^\circ$ counter-clockwise rotation send $(1,0)$ and $(0,1)$? What is its matrix?`,
      hint: R`The columns of the matrix are the images of the basis vectors.`,
      steps: [R`$(1,0)\mapsto(0,1)$ and $(0,1)\mapsto(-1,0)$.`],
      answer: R`$\begin{bmatrix}0&-1\\1&0\end{bmatrix}$.` },
    { id: "la4-3", type: "computation",
      q: R`Compute $AB$ for $A=\begin{bmatrix}1&2\\0&1\end{bmatrix}$, $B=\begin{bmatrix}3&0\\1&2\end{bmatrix}$.`,
      hint: R`Row of $A$ dotted with column of $B$.`,
      steps: [R`Row 1: $(1\cdot3+2\cdot1,\ 1\cdot0+2\cdot2) = (5,4)$.`, R`Row 2: $(0\cdot3+1\cdot1,\ 0\cdot0+1\cdot2) = (1,2)$.`],
      answer: R`$AB=\begin{bmatrix}5&4\\1&2\end{bmatrix}$.` },
    { id: "la4-4", type: "computation",
      q: R`A $3\times5$ matrix has rank 2. What is the dimension of its null space?`,
      hint: R`Rank–nullity: $\text{rank}+\text{nullity} = \#\text{columns}$.`,
      steps: [R`There are 5 columns, so $2 + \text{nullity} = 5$.`],
      answer: R`Nullity $=3$.` },
    { id: "la4-5", type: "interview",
      q: R`<strong>Deep-learning screen.</strong> A network computes $W_2(W_1\mathbf{x})$ with $W_1\in\mathbb{R}^{256\times784}$, $W_2\in\mathbb{R}^{10\times256}$ and <em>no</em> activation. Is it more expressive than a single layer? Why do we add non-linearities?`,
      hint: R`Matrix multiplication is associative.`,
      steps: [R`$W_2(W_1\mathbf{x}) = (W_2W_1)\mathbf{x}$ with $W_2W_1\in\mathbb{R}^{10\times784}$.`, R`So it is exactly one linear layer (of rank $\le256$), however deep the stack.`, R`A non-linearity such as ReLU between layers breaks the collapse and lets the network represent non-linear functions.`],
      answer: R`No — stacked linear maps collapse to one matrix; activations give depth its power.` }
  ];

  P["la-ch5"] = [
    { id: "la5-1", type: "concept",
      q: R`What does $\det A = 0$ say about the transformation $\mathbf{x}\mapsto A\mathbf{x}$?`,
      hint: R`Think of what happens to areas/volumes.`,
      steps: [R`$|\det A|$ is the factor by which areas (volumes) scale.`, R`Zero means everything is squashed into a lower dimension.`],
      answer: R`It collapses space; $A$ is singular (not invertible).` },
    { id: "la5-2", type: "concept",
      q: R`How does swapping two rows of a matrix change its determinant?`,
      hint: R`It reverses orientation.`,
      steps: [R`A row swap is a reflection-like operation.`],
      answer: R`The determinant is multiplied by $-1$.` },
    { id: "la5-3", type: "computation",
      q: R`Compute $\det\begin{bmatrix}1&2\\3&4\end{bmatrix}$.`,
      hint: R`$ad-bc$.`,
      steps: [R`$1\cdot4 - 2\cdot3 = 4-6$.`],
      answer: R`$-2$.` },
    { id: "la5-4", type: "computation",
      q: R`Compute $\det\begin{bmatrix}2&0&1\\1&3&2\\0&1&1\end{bmatrix}$ by cofactor expansion along row 1.`,
      hint: R`$2\cdot M_{11} - 0\cdot M_{12} + 1\cdot M_{13}$.`,
      steps: [R`$M_{11} = 3\cdot1 - 2\cdot1 = 1$.`, R`$M_{13} = 1\cdot1 - 3\cdot0 = 1$.`, R`$\det = 2(1) - 0 + 1(1) = 3$.`],
      answer: R`$3$.` },
    { id: "la5-5", type: "interview",
      q: R`<strong>Computational geometry.</strong> Find the area of the triangle with vertices $(0,0),\,(4,0),\,(1,3)$ using a determinant. How does this generalise to any polygon (the “shoelace formula”)?`,
      hint: R`Area $=\tfrac12\left|\det[\mathbf{a}\ \mathbf{b}]\right|$ for edge vectors $\mathbf{a},\mathbf{b}$.`,
      steps: [R`Edge vectors from the origin: $\mathbf{a}=(4,0),\ \mathbf{b}=(1,3)$.`, R`$\det\begin{bmatrix}4&1\\0&3\end{bmatrix} = 12$.`, R`Area $=\tfrac12\cdot12 = 6$.`, R`A polygon is split into triangles; summing the signed $\tfrac12\,(x_iy_{i+1}-x_{i+1}y_i)$ terms gives the shoelace formula in $O(n)$.`],
      answer: R`Area $=6$; polygon area in $O(n)$ by summing cross-product terms.` }
  ];

  P["la-ch6"] = [
    { id: "la6-1", type: "concept",
      q: R`In least squares, the residual $\mathbf{r}=\mathbf{b}-A\hat{\mathbf{x}}$ is orthogonal to what?`,
      hint: R`It is the shortest possible error vector.`,
      steps: [R`The closest point $A\hat{\mathbf{x}}$ is the orthogonal projection of $\mathbf{b}$ onto $\text{Col}(A)$.`, R`The error of a projection is perpendicular to the subspace: $A^T\mathbf{r}=\mathbf{0}$.`],
      answer: R`The column space of $A$ — which gives the normal equations $A^TA\hat{\mathbf{x}}=A^T\mathbf{b}$.` },
    { id: "la6-2", type: "concept",
      q: R`If $Q$ has orthonormal columns, what is $Q^TQ$?`,
      hint: R`Entry $(i,j)$ is $\mathbf{q}_i\cdot\mathbf{q}_j$.`,
      steps: [R`$\mathbf{q}_i\cdot\mathbf{q}_j = 1$ if $i=j$, else $0$.`],
      answer: R`The identity matrix $I$.` },
    { id: "la6-3", type: "computation",
      q: R`Project $\mathbf{b}=(3,4)$ onto the line spanned by $\mathbf{a}=(1,1)$.`,
      hint: R`$\text{proj}_{\mathbf{a}}\mathbf{b} = \frac{\mathbf{a}\cdot\mathbf{b}}{\mathbf{a}\cdot\mathbf{a}}\,\mathbf{a}$.`,
      steps: [R`$\mathbf{a}\cdot\mathbf{b} = 7,\ \mathbf{a}\cdot\mathbf{a} = 2$.`, R`Coefficient $=7/2$.`],
      answer: R`$\left(\tfrac72,\tfrac72\right)$.` },
    { id: "la6-4", type: "computation",
      q: R`Fit the line $y=mx$ through the points $(1,2),(2,3),(3,5)$ by least squares.`,
      hint: R`For one parameter, $m = \frac{\sum x_iy_i}{\sum x_i^2}$.`,
      steps: [R`$\sum xy = 2+6+15 = 23$.`, R`$\sum x^2 = 1+4+9 = 14$.`],
      answer: R`$m = 23/14 \approx 1.643$.` },
    { id: "la6-5", type: "interview",
      q: R`<strong>ML systems.</strong> You must fit linear regression with $10^6$ rows and 20 features. Compare normal equations, QR, and gradient descent.`,
      hint: R`Think cost, and conditioning: $\kappa(A^TA)=\kappa(A)^2$.`,
      steps: [R`Normal equations: form $A^TA$ in $O(nd^2)=4\cdot10^8$ flops, solve a $20\times20$ system. Fast, but squares the condition number.`, R`QR (or SVD): $O(nd^2)$ too, numerically stable — the default choice (<code>np.linalg.lstsq</code>).`, R`Gradient descent / SGD: $O(nd)$ per epoch, needed when $d$ is huge or data streams in.`],
      answer: R`Use QR/SVD at this size; normal equations if well-conditioned; SGD when $d$ or $n$ explode.` }
  ];

  P["la-ch7"] = [
    { id: "la7-1", type: "concept",
      q: R`State the defining equation of an eigenvalue $\lambda$ and eigenvector $\mathbf{v}$. Why must $\mathbf{v}\ne\mathbf{0}$?`,
      hint: R`$\mathbf{0}$ satisfies the equation for every $\lambda$.`,
      steps: [R`$A\mathbf{v}=\lambda\mathbf{v}$.`, R`$A\mathbf{0}=\lambda\mathbf{0}$ holds for <em>all</em> $\lambda$, so allowing it would make the definition meaningless.`],
      answer: R`$A\mathbf{v}=\lambda\mathbf{v}$ with $\mathbf{v}\neq\mathbf{0}$.` },
    { id: "la7-2", type: "concept",
      q: R`What are the eigenvalues of an upper-triangular matrix?`,
      hint: R`$\det(A-\lambda I)$ is a product along the diagonal.`,
      steps: [R`$A-\lambda I$ is still triangular, so its determinant is $\prod (a_{ii}-\lambda)$.`],
      answer: R`The diagonal entries.` },
    { id: "la7-3", type: "computation",
      q: R`Find the eigenvalues of $\begin{bmatrix}2&1\\1&2\end{bmatrix}$.`,
      hint: R`$\lambda^2 - (\text{trace})\lambda + \det = 0$.`,
      steps: [R`Trace $=4$, determinant $=4-1=3$.`, R`$\lambda^2 - 4\lambda + 3 = (\lambda-1)(\lambda-3)=0$.`],
      answer: R`$\lambda = 1,\ 3$.` },
    { id: "la7-4", type: "computation",
      q: R`For $A=\begin{bmatrix}2&1\\1&2\end{bmatrix}$ compute $A^{10}\begin{bmatrix}2\\0\end{bmatrix}$ using eigenvectors $(1,1)$ for $\lambda=3$ and $(1,-1)$ for $\lambda=1$.`,
      hint: R`Write $(2,0) = (1,1)+(1,-1)$.`,
      steps: [R`$A^{10}(1,1) = 3^{10}(1,1)$ and $A^{10}(1,-1) = 1^{10}(1,-1)$.`, R`$3^{10} = 59049$.`, R`Sum: $(59049+1,\ 59049-1)$.`],
      answer: R`$(59050,\ 59048)$.` },
    { id: "la7-5", type: "interview",
      q: R`<strong>PageRank.</strong> Which eigenvector does PageRank compute, for which eigenvalue, and how do you find it for a graph with $10^{10}$ pages?`,
      hint: R`The Google matrix is column-stochastic.`,
      steps: [R`The rank vector satisfies $G\mathbf{r}=\mathbf{r}$: eigenvalue $1$ (the dominant one of a stochastic matrix).`, R`Direct eigen-solvers are impossible at that size, but $G$ is sparse: use <em>power iteration</em> $\mathbf{r}_{k+1}=G\mathbf{r}_k$, one sparse mat-vec per step.`, R`Convergence rate is $|\lambda_2|/|\lambda_1|\le d$ (damping factor, ≈0.85), so ~50–100 iterations suffice.`],
      answer: R`Dominant eigenvector ($\lambda=1$) via power iteration on a sparse matrix.` }
  ];

  P["la-ch8"] = [
    { id: "la8-1", type: "concept",
      q: R`Write the SVD of $A$ and say what each factor looks like geometrically.`,
      hint: R`Rotate, stretch, rotate.`,
      steps: [R`$A=U\Sigma V^T$.`, R`$V^T$ rotates/reflects the input, $\Sigma$ stretches along axes by $\sigma_i\ge0$, $U$ rotates/reflects into the output space.`],
      answer: R`$A=U\Sigma V^T$ with $U,V$ orthogonal and $\Sigma$ diagonal non-negative.` },
    { id: "la8-2", type: "concept",
      q: R`How are the singular values of $A$ related to the eigenvalues of $A^TA$?`,
      hint: R`$A^TA = V\Sigma^2V^T$.`,
      steps: [R`$A^TA = (U\Sigma V^T)^T(U\Sigma V^T) = V\Sigma^2V^T$.`],
      answer: R`$\sigma_i = \sqrt{\lambda_i(A^TA)}$.` },
    { id: "la8-3", type: "computation",
      q: R`Find the singular values of $A=\begin{bmatrix}3&0\\4&5\end{bmatrix}$.`,
      hint: R`Eigenvalues of $A^TA$.`,
      steps: [R`$A^TA=\begin{bmatrix}25&20\\20&25\end{bmatrix}$.`, R`Eigenvalues $25\pm20 = 45,\ 5$.`, R`Take square roots.`],
      answer: R`$\sigma_1=\sqrt{45}=3\sqrt5,\ \sigma_2=\sqrt5$.` },
    { id: "la8-4", type: "computation",
      q: R`A matrix has singular values $5,3,1$. What is the Frobenius error of its best rank-1 approximation?`,
      hint: R`Eckart–Young: the error is the root-sum-square of the discarded singular values.`,
      steps: [R`Keep $\sigma_1=5$; discard $3$ and $1$.`, R`Error $=\sqrt{3^2+1^2}$.`],
      answer: R`$\sqrt{10}\approx3.16$.` },
    { id: "la8-5", type: "interview",
      q: R`<strong>Compression.</strong> A greyscale image is $1000\times1000$. How much storage does a rank-$k$ SVD approximation need for $k=50$, and what is the compression ratio?`,
      hint: R`Store $k$ columns of $U$, $k$ values of $\Sigma$, $k$ columns of $V$.`,
      steps: [R`Rank-$k$ storage: $k(1000+1000+1) = 2001k$ numbers.`, R`$k=50$: $100{,}050$ numbers vs. $10^6$.`, R`Ratio $\approx 10^6/100050 \approx 10\times$.`],
      answer: R`About $100{,}050$ numbers — roughly $10\times$ smaller (quality depends on how fast $\sigma_i$ decay).` }
  ];

  P["la-ch9"] = [
    { id: "la9-1", type: "concept",
      q: R`Define “positive definite” for a symmetric matrix $A$.`,
      hint: R`It is a statement about the quadratic form $\mathbf{x}^TA\mathbf{x}$.`,
      steps: [R`$\mathbf{x}^TA\mathbf{x}>0$ for every $\mathbf{x}\ne\mathbf{0}$.`, R`Equivalently, all eigenvalues are positive.`],
      answer: R`$\mathbf{x}^TA\mathbf{x}>0\ \forall\,\mathbf{x}\neq\mathbf{0}$ (all eigenvalues $>0$).` },
    { id: "la9-2", type: "concept",
      q: R`A symmetric matrix has eigenvalues $2$ and $-1$. What shape is the surface $z=\mathbf{x}^TA\mathbf{x}$?`,
      hint: R`Mixed signs of curvature.`,
      steps: [R`Curves up along one eigen-direction and down along the other.`],
      answer: R`A saddle; $A$ is indefinite.` },
    { id: "la9-3", type: "computation",
      q: R`Is $Q(x,y)=x^2+4xy+5y^2$ positive definite?`,
      hint: R`Write the symmetric matrix and test leading minors (Sylvester).`,
      steps: [R`$Q=\begin{bmatrix}x&y\end{bmatrix}\begin{bmatrix}1&2\\2&5\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix}$.`, R`Leading minors: $1>0$ and $\det = 5-4 = 1>0$.`],
      answer: R`Yes, positive definite.` },
    { id: "la9-4", type: "computation",
      q: R`Find the Cholesky factor $L$ (lower-triangular, $A=LL^T$) of $A=\begin{bmatrix}4&2\\2&3\end{bmatrix}$.`,
      hint: R`$L=\begin{bmatrix}l_{11}&0\\l_{21}&l_{22}\end{bmatrix}$; match entries.`,
      steps: [R`$l_{11}^2=4\Rightarrow l_{11}=2$.`, R`$l_{21}l_{11}=2\Rightarrow l_{21}=1$.`, R`$l_{21}^2+l_{22}^2=3\Rightarrow l_{22}=\sqrt2$.`],
      answer: R`$L=\begin{bmatrix}2&0\\1&\sqrt2\end{bmatrix}$.` },
    { id: "la9-5", type: "interview",
      q: R`<strong>Optimisation.</strong> For $f(x,y)=x^2+3xy+y^2$, classify the critical point at the origin. Why do saddles matter in deep-learning training?`,
      hint: R`Look at the Hessian.`,
      steps: [R`$\nabla f = \mathbf{0}$ at the origin; Hessian $H=\begin{bmatrix}2&3\\3&2\end{bmatrix}$.`, R`$\det H = 4-9=-5<0$, so eigenvalues are $5$ and $-1$: indefinite.`, R`In high dimensions, most critical points are saddles; gradient descent crawls near them, and negative-curvature directions let momentum/noise escape.`],
      answer: R`A saddle point. Saddles, not local minima, dominate high-dimensional loss surfaces.` }
  ];

  P["la-ch10"] = [
    { id: "la10-1", type: "concept",
      q: R`PCA picks directions of maximum variance. Which matrix’s eigenvectors are they?`,
      hint: R`Variance of centred data along $\mathbf{u}$ is $\mathbf{u}^T\Sigma\mathbf{u}$.`,
      steps: [R`Maximising $\mathbf{u}^T\Sigma\mathbf{u}$ with $\|\mathbf{u}\|=1$ gives the top eigenvector of $\Sigma$.`],
      answer: R`The covariance matrix; the top eigenvalues give the principal components.` },
    { id: "la10-2", type: "concept",
      q: R`For a graph Laplacian $L=D-A$, what is the sum of each row, and what is its smallest eigenvalue?`,
      hint: R`Degree minus the number of neighbours.`,
      steps: [R`Row $i$: $d_i - \sum_j A_{ij} = d_i - d_i = 0$.`, R`So $L\mathbf{1}=\mathbf{0}$: eigenvalue $0$ with eigenvector $\mathbf{1}$.`],
      answer: R`Rows sum to $0$; smallest eigenvalue is $0$.` },
    { id: "la10-3", type: "computation",
      q: R`Write the Laplacian $L=D-A$ of the path graph $1-2-3$.`,
      hint: R`Degrees are $1,2,1$.`,
      steps: [R`$D=\text{diag}(1,2,1)$, $A$ has ones at $(1,2),(2,1),(2,3),(3,2)$.`, R`Subtract entrywise.`],
      answer: R`$L=\begin{bmatrix}1&-1&0\\-1&2&-1\\0&-1&1\end{bmatrix}$.` },
    { id: "la10-4", type: "computation",
      q: R`In scaled dot-product attention with $d_k=4$, the query is $\mathbf{q}=(1,1,1,1)$ and a key is $\mathbf{k}=(1,2,3,2)$. What is the scaled score $\mathbf{q}\cdot\mathbf{k}/\sqrt{d_k}$?`,
      hint: R`Dot product first, then divide by $\sqrt{4}$.`,
      steps: [R`$\mathbf{q}\cdot\mathbf{k}=1+2+3+2=8$.`, R`$\sqrt{d_k}=2$.`],
      answer: R`$4$.` },
    { id: "la10-5", type: "interview",
      q: R`<strong>Vector search.</strong> You must find the nearest of $10^9$ embedding vectors (dimension 768) to a query, by cosine similarity, within milliseconds. How do you approach it?`,
      hint: R`Normalise vectors, then think about approximate search and dimensionality.`,
      steps: [R`Normalise every vector to unit length: then cosine similarity equals the dot product, so one matrix–vector product scores everything.`, R`Brute force costs $O(10^9\cdot768)$ per query — far too slow.`, R`Use approximate nearest-neighbour indexes (HNSW graphs, IVF clustering, product quantisation) trading a little recall for large speedups.`, R`Optionally reduce dimension with PCA/SVD to shrink memory and compute.`],
      answer: R`Unit-normalise, then ANN indexes (HNSW/IVF/PQ), optionally PCA for compression.` }
  ];

})(window.PRACTICE_DATA);
